import{a as q,S as _,i as n}from"./assets/vendor-BSTwZ_tR.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const P="https://pixabay.com/api/",$="52318710-c8f94a6f7665a4ba5885a56a6",A=15;async function h(t,r=1){const o={key:$,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:A};try{return(await q.get(P,{params:o})).data}catch(a){throw a}}const p=document.querySelector(".gallery"),u=document.querySelector(".loader"),f=document.querySelector(".load-more"),B=new _(".gallery a",{captionsData:"alt",captionDelay:250});function g(t){if(!Array.isArray(t)||t.length===0)return;const r=t.map(({webformatURL:o,largeImageURL:a,tags:e,likes:s,views:l,comments:w,downloads:S})=>`
<li class="gallery__item">
  <a class="gallery__link" href="${a}">
    <img class="gallery__image" src="${o}" alt="${e}" loading="lazy" />
  </a>
  <div class="info">
    <p class="info-item"><b>Likes</b> <span>${s}</span></p>
    <p class="info-item"><b>Views</b> <span>${l}</span></p>
    <p class="info-item"><b>Comments</b> <span>${w}</span></p>
    <p class="info-item"><b>Downloads</b> <span>${S}</span></p>
  </div>
</li>`).join("");p.insertAdjacentHTML("beforeend",r),B.refresh()}function H(){p.innerHTML=""}function L(){u&&u.classList.remove("is-hidden")}function m(){u&&u.classList.add("is-hidden")}function b(){f&&f.classList.add("is-visible")}function c(){f&&f.classList.remove("is-visible")}let d="",i=1,y=0;const E=15,v=document.querySelector(".form"),M=v.querySelector('input[name="search-text"]'),O=document.querySelector(".load-more"),x=document.querySelector(".gallery");v.addEventListener("submit",async t=>{t.preventDefault();const r=M.value.trim();if(!r){n.info({title:"Info",message:"Please enter a search query."});return}r!==d&&(d=r,i=1,H(),c());try{L();const o=await h(d,i);if(m(),!o.hits||o.hits.length===0){n.warning({title:"No results",message:"No images found. Try another query."}),c();return}i===1&&(y=o.totalHits||0,n.success({title:"Success",message:`Hooray! We found ${y} images.`})),g(o.hits),i*E<y?b():(c(),n.info({title:"End",message:"We're sorry, but you've reached the end of search results."}))}catch(o){m(),n.error({title:"Error",message:"Something went wrong. See console."}),console.error("Error fetching images:",o)}});O.addEventListener("click",async()=>{i+=1;try{L();const t=await h(d,i);if(m(),!t.hits||t.hits.length===0){c(),n.info({title:"End",message:"We're sorry, but you've reached the end of search results."});return}g(t.hits);const r=x.querySelector(".photo-card");if(r){const{height:a}=r.getBoundingClientRect();window.scrollBy({top:a*2,left:0,behavior:"smooth"})}i*E>=(t.totalHits||0)?(c(),n.info({title:"End",message:"We're sorry, but you've reached the end of search results."})):b()}catch(t){m(),n.error({title:"Error",message:"Failed to load more images."}),console.error("Load more error:",t)}});
//# sourceMappingURL=index.js.map
